/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jinji_internetproj_ShowIpPort_Connect */

#ifndef _Included_com_example_jinji_internetproj_ShowIpPort_Connect
#define _Included_com_example_jinji_internetproj_ShowIpPort_Connect
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_jinji_internetproj_ShowIpPort_Connect_MIN_PRIORITY
#define com_example_jinji_internetproj_ShowIpPort_Connect_MIN_PRIORITY 1L
#undef com_example_jinji_internetproj_ShowIpPort_Connect_NORM_PRIORITY
#define com_example_jinji_internetproj_ShowIpPort_Connect_NORM_PRIORITY 5L
#undef com_example_jinji_internetproj_ShowIpPort_Connect_MAX_PRIORITY
#define com_example_jinji_internetproj_ShowIpPort_Connect_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
