/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jinji_internetproj_piano_recvSocket */

#ifndef _Included_com_example_jinji_internetproj_piano_recvSocket
#define _Included_com_example_jinji_internetproj_piano_recvSocket
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_jinji_internetproj_piano_recvSocket_MIN_PRIORITY
#define com_example_jinji_internetproj_piano_recvSocket_MIN_PRIORITY 1L
#undef com_example_jinji_internetproj_piano_recvSocket_NORM_PRIORITY
#define com_example_jinji_internetproj_piano_recvSocket_NORM_PRIORITY 5L
#undef com_example_jinji_internetproj_piano_recvSocket_MAX_PRIORITY
#define com_example_jinji_internetproj_piano_recvSocket_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
